version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      react:
        patterns:
          - react
          - react-dom
          - '@types/react'
          - '@types/react-dom'
      fullcalendar:
        patterns:
          - '@fullcalendar/*'
      typescript-eslint:
        patterns:
          - '@typescript-eslint/*'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
